settings:
  server:
    host: "0.0.0.0"
    port: 9999
    threads: 8

modules:
  /auth: #i.e. http://localhost:9999/auth
    mode: local
    
    method: basic
    realm: default users

    local:
      db_path: /config/users.yml
      allowed_roles:
      - default

  /auth/admin: #i.e. http://localhost:9999/auth/admin
    mode: local
    
    method: basic
    realm: admin users

    local:
      db_path: /config/users.yml
      allowed_roles:
      - admin

  /auth/local: #i.e. http://localhost:9999/auth
    mode: local
    
    method: basic
    realm: default users

    local:
      db_path: /config/users.yml
      allowed_roles:
      - default


  /auth/upstream: #i.e. http://localhost:9999/auth/upstream
    mode: upstream # do the password checking in upstream

    method: basic
    realm: upstream users

    upstream:
      url: https://demo.jellyfin.org/stable/Users/authenticatebyname
      data: >-
        {"Username":"<<username>>","Pw":"<<password>>"}
      # json:
      #   Username: <<username>>
      #   Pw: <<password>>
      headers:
        Content-Type: application/json
        X-Emby-Authorization: MediaBrowser Client="nginx", Device="server", DeviceId="0", Version="1.0.0"

        # Forward the following list of request header to upstream server
        __forward:
        - X-Forwarded-For
        - X-Forwarded-Host
        - X-Forwarded-Method
        - X-Forwarded-Port
        - X-Forwarded-Proto
        - X-Forwarded-Server
        - X-Forwarded-Ss
        - X-Forwarded-Uri
        - X-Original-Method
        - X-Original-URL
        - X-Real-IP

  /auth/dynamic: #i.e. http://localhost:9999/auth/upstream
    mode: dynamic # do the password checking in upstream

    method: basic
    realm: dynamic users

    local:
      db_path: /config/users.yml
      allowed_roles:
      - admin
      - default

    upstream:
      url: https://demo.jellyfin.org/stable/Users/authenticatebyname
      data: >-
        {"Username":"<<username>>","Pw":"<<password>>"}
      # json:
      #   Username: <<username>>
      #   Pw: <<password>>
      headers:
        Content-Type: application/json
        X-Emby-Authorization: MediaBrowser Client="nginx", Device="server", DeviceId="0", Version="1.0.0"

        # Forward the following list of request header to upstream server
        __forward:
        - X-Forwarded-For
        - X-Forwarded-Host
        - X-Forwarded-Method
        - X-Forwarded-Port
        - X-Forwarded-Proto
        - X-Forwarded-Server
        - X-Forwarded-Ss
        - X-Forwarded-Uri
        - X-Original-Method
        - X-Original-URL
        - X-Real-IP